### ISSUE TITLE
Error while reading TTF font without post table

### ISSUE THREAD

**Issue by astefanutti** [kekee000/fonteditor-core#11]
Reading a TTF font without a post table produces the following error:

```
TypeError: Cannot convert undefined or null to object
    at TTFReader.cleanTables (/Users/astefanu/Development/decktape/node_modules/fonteditor-core/ttf/ttfreader.js:156:15)
    at TTFReader.read (/Users/astefanu/Development/decktape/node_modules/fonteditor-core/ttf/ttfreader.js:210:17)
    at Font.read (/Users/astefanu/Development/decktape/node_modules/fonteditor-core/ttf/font.js:101:44)
    at new Font (/Users/astefanu/Development/decktape/node_modules/fonteditor-core/ttf/font.js:56:14)
    at Function.Font.create (/Users/astefanu/Development/decktape/node_modules/fonteditor-core/ttf/font.js:335:12)
    at parseFont (/Users/astefanu/Development/decktape/decktape.js:410:24)
    at Array.forEach (<anonymous>)
    at parseResources (/Users/astefanu/Development/decktape/decktape.js:452:50)
    at parseXObject (/Users/astefanu/Development/decktape/decktape.js:374:7)
    at Array.forEach (<anonymous>)
```

**Comment by astefanutti** [comment]
Fixed in bcf48d32ab48317b9a5f7b77c31ae6dd6532ec6e.
