### ISSUE TITLE
Our Node app is frequently getting killed with an npm error

### ISSUE THREAD

**Issue by kanirajan2530** [kekee000/fonteditor-core#68]
### Description
**If facing an unhandled rejection error in our project, Node has been killed due to an npm error like this:**

>abort(ReferenceError: count is not defined) at Error
    at jsStackTrace (D:\Practice\node_modules\fonteditor-core\woff2\woff2.js:8:22498)
    at stackTrace (D:\Practice\node_modules\fonteditor-core\woff2\woff2.js:8:22669)
    at process.abort (D:\Practice\node_modules\fonteditor-core\woff2\woff2.js:8:18310)
    at process.emit (node:events:514:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v18.17.0

**Environment**

- Node version: v18.17.0
- Npm version: 9.6.7

**Comment by kekee000** [comment]
Could you provide  a min reproduce code.
You can use child process or worker_threads to handle woff2 conversion, avoid process exiting on error.

**Comment by kanirajan2530** [comment]
**This code we are using for our project**

> const { Font, woff2 } =require("fonteditor-core");
const fs = require("fs");
const buffer = fs.readFileSync("../inputs/material.woff2");
woff2.init().then(() => {
  const font = Font.create(buffer, {
    type: "woff2",
    subset: [
      0xeb4e, 0xec17
    ],
  });
  const fontObject = font.get();
  const writeBuffer = font.write({
    type: "woff2",
  });
  const fontFilePath = '../outputs/system_icons.woff2';
  fs.writeFileSync(fontFilePath, writeBuffer, {});
});
